[domain]
tld = "rocks"
name = "rdil"
dnssec = true
provider = "Cloudflare"

[[records]]

[[records.txt]]

[[records.txt.git]]
hostname = "git"
value = "https://github.com/RDIL"
cloudflare_is_proxied = true

[[records.txt."@"]]
hostname = "@"
value = "v=spf1 include:_spf.google.com ~all"
cloudflare_is_proxied = true

[[records.txt._dmarc]]
hostname = "_dmarc"
value = "v=DMARC1; p=quarantine; pct=5; rua=mailto:me@rdil.rocks"
cloudflare_is_proxied = true

[[records.mx]]

[[records.mx.main]]
hostname = "@"
location = "aspmx.l.google.com"
priority = 1

[[records.mx.alt1]]
hostname = "@"
location = "alt1.aspmx.l.google.com"
priority = 5

[[records.mx.alt2]]
hostname = "@"
location = "alt2.aspmx.l.google.com"
priority = 5

[[records.mx.alt3]]
hostname = "@"
location = "alt3.aspmx.l.google.com"
priority = 10

[[records.mx.alt4]]
hostname = "@"
location = "alt4.aspmx.l.google.com"
priority = 10

[[records.a]]

[[records.a.docs1]]
hostname = "docs"
location = "185.199.108.153"
cloudflare_is_proxied = true

[[records.a.docs2]]
hostname = "docs"
location = "185.199.109.153"
cloudflare_is_proxied = true

[[records.a.docs3]]
hostname = "docs"
location = "185.199.110.153"
cloudflare_is_proxied = true

[[records.a.docs4]]
hostname = "docs"
location = "185.199.111.153"
cloudflare_is_proxied = true

[[records.a."@"]]
hostname = "@"
location = "104.198.14.52"
cloudflare_is_proxied = true

[[records.cname]]

[[records.cname.www]]
hostname = "www"
location = "rdil.netlify.app"
cloudflare_is_proxied = true

[[records.cname.privacy]]
hostname = "privacy"
location = "rdil-privacy.netlify.app"
cloudflare_is_proxied = true

[[records.cname.backend]]
hostname = "backend"
location = "webapp-598447.pythonanywhere.com"
cloudflare_ruleset = "CUSTOM"

[[records.cname.cirrusbuilder]]
hostname = "cirrusbuilder"
location = "cirrusbuilder.netlify.app"
cloudflare_is_proxied = true

[[records.spf]]

[[records.spf."@"]]
hostname = "@"
ttl = 3600
value = "v=spf1 include:_spf.google.com ~all"
